version: '3.8'
services:
  # Redis 服务定义
  redis:
    image: redis:6.0.7
    container_name: redisForYubi
    restart: always
    volumes:
      - redis_volume_data:/dataForYubi
    ports:
      - "6379:6379"
#
#  redis_insight:
#    image: redislabs/redisinsight:1.14.0
#    container_name: redis_insight
#    restart: always
#    ports:
#      - "8001:8001"
#    volumes:
#      - redis_insight_volume_data:/db

  # RabbitMQ service definition
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  redis_volume_data: